### ISSUE TITLE
noProgress param doesn't install packages without progress

### ISSUE THREAD

**Issue by luukholleman** [warapitiya/gulp-yarn#2]
```
gulp.src(glob)
	.pipe(yarn({
		noProgress: true
	}));
```

This doesn't install the packages as `yarn install --no-progress`. Am I doing something wrong or is this not supported yet?

**Comment by warapitiya** [comment]
@luukholleman this is not yet supported. Will be available from next release.

**Comment by warapitiya** [comment]
@luukholleman Happy to tell you that we added this options.

For more supported options, go through [README](https://github.com/warapitiya/gulp-yarn/blob/master/README.md). :metal:

**Comment by luukholleman** [comment]
Thanks!
