### ISSUE TITLE
Allow passthrough of args

### ISSUE THREAD

**Issue by glebec** [warapitiya/gulp-yarn#3]
Instead of manually implementing arguments in the options object, please allow straightforward passing of any argument to the underlying `yarn` command. For example, I want to use `--ignore-scripts`. Instead of relying on an API to do that for me, why not something like `.pipe(yarn({ args: ['--ignore-scripts'] })`?

**Comment by warapitiya** [comment]
@glebec really like your idea but there will be no validation of any commands you pass to yarn. What you need is behavior of [gulp-run](https://www.npmjs.com/package/gulp-run) plugin.

**Comment by glebec** [comment]
Thanks for the response. It's true that there wouldn't be any command validation by `gulp-yarn` if you did a "blind" passthrough like I am asking. However, there would still be the error thrown by `yarn` itself if passed an argument it does not understand. To me that's enough, though I can understand the argument that `gulp-yarn` itself could supply more expressive errors. It just seems needless to replicate the entire API of `yarn` for the sake of argument passing — my humble opinion.

Feel free to close this issue if you like. And thanks for merging the PR!

**Comment by warapitiya** [comment]
@glebec I really like your argument here. In fact, It's true in a way. We could probably implement this solution, so that depends on user using it or not. I need to further dig into this. I'm keeping this issue open until I get a solid solution for this.

Thanks.

**Comment by glebec** [comment]
Sure thing. You might want to check out [gulp-spawn-mocha](https://github.com/knpwrs/gulp-spawn-mocha) — they build the args from the option object keys dynamically using `-` or `--` as appropriate for single-letter and multi-letter arguments.

**Comment by warapitiya** [comment]
Hi @glebec, really excited to tell you that I impemented this feature and it's in alpha release [v1.0.0-alpha.2](https://github.com/warapitiya/gulp-yarn/tree/v1.0.0-alpha.2).

#### Install :
```sh
$ yarn add gulp-yarn@alpha -D
```

#### Usage :
Options 1 | Array
```js
yarn({
    args: [
        '--version'
    ]
});
```

Options 2 | String
```js
yarn({
    args: '--version'
});
```
FYI: if you have an issues report them and README.md will be update soon.

**Comment by glebec** [comment]
Wonderful! I especially like that you support both array and string formats. I'll check this out later but in the meantime thanks for the work.
