### ISSUE TITLE
Args

### ISSUE THREAD

**Issue by MarkCiliaVincenti** [warapitiya/gulp-yarn#51]
If you try to pass on arguments that have values, it seems that gulp-yarn ends up prepending the value with '--'

so if you tell it:
````
--registry https://www.google.com
````

it actually sends this to Yarn:
````
--registry --https://www.google.com
````

**Comment by warapitiya** [comment]
Published: [4.0.1](https://www.npmjs.com/package/gulp-yarn/v/4.0.1)
